### ISSUE TITLE
安装包为什么不能下载了呢

### ISSUE THREAD

**Issue by tu6ge** [mxismean/image-tiny-tauri#1]

**Comment by mxismean** [comment]
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/44690729/187584097-1dc8daf7-5182-4de4-b351-efd8d24b885f.png">
可以下载啊

**Comment by mxismean** [comment]
https://github.com/mxismean/image-tiny-tauri/releases
从这里直接下载

**Comment by tu6ge** [comment]
![image](https://user-images.githubusercontent.com/4115242/187600007-6165547e-3bb4-492f-8230-721e918b0fd0.png)

**Comment by tu6ge** [comment]
Draft 是草稿，只能你自己看到

**Comment by mxismean** [comment]
> 

已经发布了， 这次可以下载了😅
谢谢你的提醒，感谢🙏
