### ISSUE TITLE
有安全风险提示

### ISSUE THREAD

**Issue by tu6ge** [mxismean/image-tiny-tauri#2]
![image](https://user-images.githubusercontent.com/4115242/187859237-129f2689-9acf-4c2d-8d0b-f0631cb5a321.png)

**Comment by mxismean** [comment]
仍要运行就行，因为不是通过正规应用市场发的包所以会有安全提示


mx-163

**Comment by tu6ge** [comment]
可以根据这个 [文档](https://tauri.app/v1/guides/distribution/updater) 的说明，做个签名，会好些

**Comment by tu6ge** [comment]
我试了下我自己的包，也有同样的问题，解决方案不对

**Comment by mxismean** [comment]
多谢，我看看加一下😄

mx-163

**Comment by tu6ge** [comment]
我之前找过方案，没有人民币解决不了，你有方案的话，分享下

**Comment by mxismean** [comment]
> 

暂时好像没啥解决方案，还是需要 RMB 加持才行，反正也不上应用市场，能用就行
