### ISSUE TITLE
拖放图片落点不在中间区域，就变成了直接打开图片了，导致只能关闭应用，才能再次使用

### ISSUE THREAD

**Issue by yasyas001** [mxismean/image-tiny-tauri#4]

**Comment by mxismean** [comment]
可以录个gif我看一下具体是啥样的？mx-163在 2023年3月21日，18:54，yasyas001 ***@***.***> 写道：﻿

**Comment by yasyas001** [comment]
gif放不进来，就是把图片拖到窗口的列表栏的标题栏和最下面的功能栏位置，然后松开鼠标，我是mac电脑

**Comment by mxismean** [comment]
标题栏和功能栏不在拖放区域内的。你说的变成直接打开图片是啥意思？系统图片预览了嘛？还有就是对应用的影响是啥？为啥需要关闭应用才能再次使用？这个没太明白mx-163在 2023年3月21日，19:31，yasyas001 ***@***.***> 写道：﻿
gif放不进来，就是把图片拖到窗口的列表栏的标题栏和最下面的功能栏位置，然后松开鼠标，我是mac电脑

**Comment by mxismean** [comment]
或者你截几张不同状态的图进来我看看mx-163在 2023年3月21日，19:31，yasyas001 ***@***.***> 写道：﻿
gif放不进来，就是把图片拖到窗口的列表栏的标题栏和最下面的功能栏位置，然后松开鼠标，我是mac电脑

**Comment by yasyas001** [comment]
![QQ20230321-190322](https://user-images.githubusercontent.com/12994305/226788581-e522d4d0-eb5e-4fa2-b040-01da47594710.gif)

**Comment by mxismean** [comment]
好的，我最近修复一下，感谢反馈

**Comment by mxismean** [comment]
新版本已经发布了: V0.2.3
底部操作栏和中间区域目前都已经好了。
但是 title bar 还是会打开文件，这个应该是 Tauri 的bug，已经给 Tauri 提bug了，等tauri 给出解决方案之后，会再更新个版本

**Comment by mxismean** [comment]
@yasyas001
